---

# Creo que bastaría con eliminar el grupo health y eliminar el usuario salud.

- hosts: local
  connection: local
  become: True
  gather_facts: False
  user: ansible


  tasks:
  - name: ELIMINANDO EL GRUPO health 
    group:
      name: health
      state: absent
 
  - name: ELIMINANDO el usuario salud
    user:
       name: "{{ item }}"
       comment: "usuario para los scripts de salud"
       state: absent
    with_items:
      - salud
