--- 
- name: DOWNLOAD PROCESS
  hosts: local
  user: ansible
  become: true
  connection: local

  roles:
    - role: sshpassDownload
      v_usr: usuario
      v_pass: pass 
      v_server: server
      v_remotePath: /path1/path2/
      v_localPath: /path3/path4



