--- 
# Este playbook requiere de los roles:
# - sshpassDownload
# - installHisto
#
# Funcionalidad:
# - Descargar del sftp las versiones de historificacion .zip.
# - Instalar y configurar.
# 
# El fichero inventory del que tira es:
# - /etc/ansible/hosts

- name: DOWNLOAD PROCESS
  hosts: local
  user: ansible
  become: true
  connection: local

  roles:
    - role: sshpassDownload
      v_usr: xx
      v_pass: xx 
      v_server: xx
      v_remotePath: xx
      v_localPath: xx

- name: INSTALL PROCESS
  hosts: historificacion
  user: ansible
  become: true
  connection: ssh

  roles:
       #---------------------------------------------------
       #Historificacion en la maquina 180.101.180.155
       #---------------------------------------------------

    - { role: installHisto, laMaquina: 'ISLMDDWC01', rutaRemotaComprimido: '/historif/ansible' , usuario: 'historif'}
    - { role: installHisto, laMaquina: 'ISLMDDWC01', rutaRemotaComprimido: '/usr/inst1/ansible', usuario: 'inst1' }

       #---------------------------------------------------
       #Historificacion en la maquina 180.197.76.209
       #---------------------------------------------------

    - { role: installHisto, laMaquina: 'OCLDB2D208', rutaRemotaComprimido: '/usr/inst3/ansible', usuario: 'inst3' }
